name = input("what is your name?")
print("")
print(f"Hello {name} today we will be writing a story with the word you pick!")
print("")
person = input("pick a person")
print("")
location = input ("now pick a location")
print("")
verb = input ("now pick a verb ending in ing ")
print("")
animal = input("animal")
print("")
type_of_transportation = input ("pick a type of transportation")
print("")
location2 = input("pick another location")
print("")
adjective = input ("adjective")
print("")
animal2 = input ("animal2")
print("")
print(f"one day {person} was seen in {location} and they were {verb} but then they got attacked by a {animal} so they took the {type_of_transportation} and went to {location2} but then they saw a {adjective} {animal2} that they made friends  with ")



