name = input("what is your name?")
print("")
print(f"Hello {name} today we will be writing a story with the word you pick!")
print("")
person = input("pick a person")
print("")
location = input ("now pick a location")
print("")
verb = input ("now pick a verb ending in ing ")
print("")
print (f"one day{person} was seen {verb} in {location} ") 
print ("")
animal = input("animal")
print(f"but then a {animal} attacked them ")